Use JDK 11 for spotless (#4697)
spotlessCheck is flaky when using JDK 8. It sometimes gives this error:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dd-trace-ot:spotlessGroovy'.
        [...]
Caused by: com.diffplug.spotless.ThrowingEx$WrappedAsRuntimeException: java.lang.Exception: You are running Spotless on JVM 8, which limits you to eclipse groovy formatter 4.19.0.
If you upgrade your JVM to 11+, then you can use eclipse groovy formatter 4.21.0, which may have fixed this problem.
       [...]
Caused by: java.lang.Exception: You are running Spotless on JVM 8, which limits you to eclipse groovy formatter 4.19.0.
If you upgrade your JVM to 11+, then you can use eclipse groovy formatter 4.21.0, which may have fixed this problem.
	at com.diffplug.spotless.Jvm$Support$1.apply(Jvm.java:181)
	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:82)
	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
	at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
	... 151 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at com.diffplug.spotless.extra.eclipse.groovy.GrEclipseFormatterStepImpl$GroovyErrorListener.<init>(GrEclipseFormatterStepImpl.java:109)
	at com.diffplug.spotless.extra.eclipse.groovy.GrEclipseFormatterStepImpl.format(GrEclipseFormatterStepImpl.java:83)
	at com.diffplug.spotless.extra.groovy.GrEclipseFormatterStep.lambda$apply$0(GrEclipseFormatterStep.java:57)
	at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
	at com.diffplug.spotless.Jvm$Support$1.apply(Jvm.java:179)
	... 154 more
```