fix: Failing :dd-java-agent:agent-ci-visibility
When Groovy compiles this code against JDK 21 **but targeting Java 8**,

```
private static final class MisbehavingClassLoader extends ClassLoader { ... }
```

Groovy will generate super class synthetic accessor methods like

* `super$2$loadClass(Ljava/lang/String;)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/String;Z)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/Module;Ljava/lang/String;)Ljava/lang/Class;`

`java.lang.Module` being missing from Java 8 won't run.

java.lang.NoClassDefFoundError: java/lang/Module
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.privateGetPublicMethods(Class.java:2930)
	at java.lang.Class.getMethods(Class.java:1643)
	at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
	at java.beans.Introspector.getBeanInfo(Introspector.java:426)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at datadog.trace.civisibility.source.ByteCodeLinesResolverTest.test returns empty method lines when class cannot be loaded(ByteCodeLinesResolverTest.groovy:45)
Caused by: java.lang.ClassNotFoundException: java.lang.Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more