fix(ci): Dedicated spotless config on test-publihsed-artifacts
The spotless _plugin script_, is being reused in
test-published-artifacts, unfortunately spotless a serilization bug
on the greclipse formatter that surfaces when no files mathing
extension target. This causes the build to fail with a obscure error
related to fingerprinting:

```
java.lang.IllegalStateException: If the initializer was null, then one of
roundtripStateInternal or equalityStateInternal should be non-null, and neither was
    at com.diffplug.spotless.FormatterStepSerializationRoundtrip.writeObject(...)
    at com.diffplug.spotless.ConfigurationCacheHackList.hashCode(...)
```

This change applies a tailored configuration for this simple project.