Avoids NoClassDefFoundError: Could not initialize class DDSpanLink$EncoderHolder in Graal native-image (#8036)
Both fromJson and toJson methods need to be registered, do the same for other JSON entries to be consistent.

Also declare some JsonRule types need reflective access for a related issue using DD_TRACE_SAMPLING_RULES