Fix publishing to artifactory...
Newer versions fail when publishing with the exception:
```
Caused by: java.lang.NoSuchMethodError: org.apache.http.impl.client.HttpClientBuilder.setPublicSuffixMatcher(Lorg/apache/http/conn/util/PublicSuffixMatcher;)Lorg/apache/http/impl/client/HttpClientBuilder;
```

https://www.jfrog.com/jira/browse/GAP-317