Decouple Gradle JDK from JDK8 (#9514)
* Set default java toolchain to 8

* Set toolchain early

* Set JAVA_HOME for smoke test builds

* Do not set compiler release by default (remove skipSettingCompilerRelease)

# Conflicts:
#	internal-api/build.gradle was converted to internal-api/build.gradle.kts

# Conflicts:
#	dd-java-agent/instrumentation/java-concurrent/java-completablefuture/build.gradle

* build: Run instrument plugin with toolchain

# Conflicts:
#	buildSrc/src/main/groovy/MuzzlePlugin.groovy

# Conflicts:
#	buildSrc/src/main/kotlin/datadog/gradle/plugin/muzzle/MuzzleTask.kt

* build: Check version in CI

* fix: call-instrumentation-site test due to the appearance of SequenceCollection::getFirst in JDK 21

* chore: Explicit setup of the compiler

# Conflicts:
#	dd-java-agent/instrumentation/kafka/kafka-clients-3.8/build.gradle

# Conflicts:
#	dd-java-agent/agent-profiling/profiling-controller-jfr/build.gradle
#	dd-java-agent/instrumentation/play/play-2.6/build.gradle
#	dd-java-agent/instrumentation/wildfly-9.0/build.gradle
#	dd-smoke-tests/concurrent/java-25/build.gradle
#	utils/socket-utils/build.gradle.kts

# Conflicts:
#	dd-java-agent/agent-bootstrap/build.gradle
#	dd-java-agent/agent-builder/build.gradle
#	dd-java-agent/agent-profiling/profiling-controller-jfr/build.gradle
#	dd-java-agent/instrumentation/akka/akka-http/akka-http-10.6/build.gradle
#	dd-java-agent/instrumentation/exception-profiling/build.gradle
#	dd-java-agent/instrumentation/graal/native-image/build.gradle
#	dd-java-agent/instrumentation/jetty/jetty-server/jetty-server-12.0/build.gradle
#	dd-java-agent/instrumentation/kafka/kafka-clients-3.8/build.gradle
#	dd-java-agent/instrumentation/liberty-20/build.gradle
#	dd-java-agent/instrumentation/micronaut/http-server-netty-4.0/build.gradle
#	dd-java-agent/instrumentation/play/play-2.6/build.gradle
#	dd-java-agent/instrumentation/spring/spring-scheduling-3.1/build.gradle
#	dd-java-agent/instrumentation/spring/spring-webmvc/spring-webmvc-6.0/build.gradle
#	dd-java-agent/instrumentation/vertx/vertx-web/vertx-web-4.0/build.gradle
#	dd-java-agent/instrumentation/websocket/jetty-websocket/jetty-websocket-10/build.gradle
#	dd-java-agent/instrumentation/wildfly-9.0/build.gradle

* refactor: setJavaVersion becomes configureCompiler, handles release/source/target

# Conflicts:
#	dd-java-agent/agent-tooling/build.gradle

* fix: project.afterEvaluate messing with setting up "testJvm"

* fix: duplicated task config

* fix: Failing :dd-java-agent:agent-tooling tests

When Groovy compiles this code against JDK 21 **but targeting Java 8**,

```
URLClassLoader loader = new URLClassLoader(classpath, null, null) {
    @Override
    Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        ...
    }
  }
```

Groovy will generate super class synthetic accessor methods like

* `super$2$loadClass(Ljava/lang/String;)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/String;Z)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/Module;Ljava/lang/String;)Ljava/lang/Class;`

`java.lang.Module` being missing from Java 8 won't run.

java.lang.NoClassDefFoundError: java/lang/Module
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.privateGetPublicMethods(Class.java:2930)
	at java.lang.Class.getMethods(Class.java:1643)
	at groovy.lang.MetaClassImpl.inheritInterfaceNewMetaMethods(MetaClassImpl.java:628)
	at groovy.lang.MetaClassImpl.fillMethodIndex(MetaClassImpl.java:368)
	at groovy.lang.MetaClassImpl.reinitialize(MetaClassImpl.java:3381)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3376)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:273)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:315)
	at datadog.trace.agent.test.BaseExceptionHandlerTest$1.$getStaticMetaClass(BaseExceptionHandlerTest.groovy)
	at datadog.trace.agent.test.BaseExceptionHandlerTest$1.<init>(BaseExceptionHandlerTest.groovy)
	at datadog.trace.agent.test.BaseExceptionHandlerTest.$spock_feature_1_1(BaseExceptionHandlerTest.groovy:131)
	...
Caused by: java.lang.ClassNotFoundException: java.lang.Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	...

* fix: Failing :dd-java-agent:agent-ci-visibility

When Groovy compiles this code against JDK 21 **but targeting Java 8**,

```
private static final class MisbehavingClassLoader extends ClassLoader { ... }
```

Groovy will generate super class synthetic accessor methods like

* `super$2$loadClass(Ljava/lang/String;)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/String;Z)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/Module;Ljava/lang/String;)Ljava/lang/Class;`

`java.lang.Module` being missing from Java 8 won't run.

java.lang.NoClassDefFoundError: java/lang/Module
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.privateGetPublicMethods(Class.java:2930)
	at java.lang.Class.getMethods(Class.java:1643)
	at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
	at java.beans.Introspector.getBeanInfo(Introspector.java:426)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at datadog.trace.civisibility.source.ByteCodeLinesResolverTest.test returns empty method lines when class cannot be loaded(ByteCodeLinesResolverTest.groovy:45)
Caused by: java.lang.ClassNotFoundException: java.lang.Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more

* fix: Fix Groovy delegation that was adding interfaces to object delegation.

There was a `NoClassDefFoundError` of `java.lang.constant.Constable` when run on JDK8, this happened
because the `Delegate` annotation makes Groovy adds the interfaces of the delegated object to the
enclosing class. Since JDK12 types like `Integer`, `String` implement `Constable` this fails
when the class is loaded on JDK8 or 11.
See https://github.com/groovy/groovy-eclipse/issues/1436

java.lang.NoClassDefFoundError: java/lang/constant/Constable
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.datadog.appsec.event.data.ObjectIntrospectionSpecification.conversion of an element throws(ObjectIntrospectionSpecification.groovy:305)
Caused by: java.lang.ClassNotFoundException: java.lang.constant.Constable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more

* fix: Fix muzzle detected that compiler generated an invokeinterface for getClass on HttpRequest

Instead, the byte code is now an invokevirtual on Object as the javac in JDK8 does

* fix: Fix jdbc tests because `java.sql.Connection` introduced methods with new types in JDK9

E.g. methods with `java.sql.ShardingKey`, while these methods are default, Groovy still
implements them (implementation actually invokes the interface default method).

org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 66.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:65)
	...
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:165)
	...
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'foo.bar.IastInstrumentedConnection', classLoader = sun.misc.Launcher$AppClassLoader@73d16e93] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
	...
Caused by: java.lang.NoClassDefFoundError: java/sql/ShardingKey
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.privateGetPublicMethods(Class.java:2930)

* fix: dd-smoke-tests needs to use Java 8

ProcessManager uses the `CharBuffer.flip` method, which is
coming from the super class in JDK 8 so its signature is
`()Ljava.nio.Buffer`, but since JDK9 `CharBuffer` overrides
it, in the bytecode the signatures becomes `()Ljava.nio.CharBuffer`.

This code fails when running with testJvm=8.

* chore: Make spotless happy

* fix: iast-agent was not using configureCompiler

* fix: Make resilience4j modules use configureCompiler

* fix: Replace Groovy's getProperty by Project.findProperty

* fix: vertx-web-5.0 now uses configureCompiler

* fix: smoke appsec/springboot-graphql needs to compile to Java 1.8

* chore: fail early when testJvm is blank

* fix: Enforce ByteCode 1.8 on some jetty projects

* style: Typo

* Revert "fix: Fix muzzle detected that compiler generated an invokeinterface for getClass on HttpRequest"

This reverts commit bc1b15c1c8d645e9dff7baad9757b4c7067a4d5f because muzzle now handles
https://bugs.openjdk.org/browse/JDK-8272715 since #9649

---------

Co-authored-by: Santiago Mola <santiago.mola@datadoghq.com>