Fix GitClientTest.test git diff when diff.noprefix=true is used (#10299)
When diff.noprefix=true (or other git diff parameters that change
the prefix format) used, it changes the output from "git diff" and
and the test failure below is seen in GitClientTest.test git diff.
I have used this git setting in my ~/.gitconfig file for years as
it makes copying and pasting file names simpler.

java.lang.IllegalStateException: Line @@ -26 +26 @@ namespace Datadog.Trace.Logging contains changed lines information, but no changed file info is available
	at datadog.trace.civisibility.git.tree.GitDiffParser.parse(GitDiffParser.java:48)
	at datadog.trace.civisibility.utils.ShellCommandExecutor.executeCommand(ShellCommandExecutor.java:153)
	at datadog.trace.civisibility.utils.ShellCommandExecutor.executeCommand(ShellCommandExecutor.java:57)
	at datadog.trace.civisibility.git.tree.ShellGitClient.lambda$getGitDiff$18(ShellGitClient.java:926)
	at datadog.trace.civisibility.git.tree.ShellGitClient.executeCommand(ShellGitClient.java:980)
	at datadog.trace.civisibility.git.tree.ShellGitClient.getGitDiff(ShellGitClient.java:923)
	at datadog.trace.civisibility.git.tree.GitClientTest.test git diff(GitClientTest.groovy:264)

Setting diff.noprefix=true changes the file name pattern and it
fails to match GitDiffParser.CHANGED_FILE_PATTERN.

$ git diff | grep ^diff
diff --git a/dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/ShellGitClient.java b/dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/ShellGitClient.java

$ GIT_CONFIG_PARAMETERS="'diff.noprefix=true'" git diff | grep ^diff
diff --git dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/ShellGitClient.java dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/ShellGitClient.java

Notice the lack of "a/" and "b/" on the latter output, but you'll see
that the pattern expects that:

  private static final Pattern CHANGED_FILE_PATTERN =
      Pattern.compile("^diff --git a/(?<oldfilename>.+) b/(?<newfilename>.+)$");

The simple workaround is to pass "--default-prefix" to "git diff",
however this option has only been present since 2023:

https://github.com/git/git/commit/b39a5697296659c344cd0a286b51303fd5375fab

A safer option would be to use "--no-prefix", which has existed since
2007:

https://github.com/git/git/commit/eab9a40b6dd5c1c571b1deb264133db47bb4794d

This adds "--no-prefix", updates the regex, and adjusts test files.

Co-authored-by: DJ Gregor <dj@gregor.com>