Tests in dd-trace-core should extend DDSpecification
It has a work around to ensure Config is modifiable before it is loaded and if Config is loaded before hand, it can cause other tests to fail.
For example:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class datadog.trace.util.test.DDSpecification
```