fix: Fix Groovy delegation that was adding interfaces to object delegation.
There was a `NoClassDefFoundError` of `java.lang.constant.Constable` when run on JDK8, this happened
because the `Delegate` annotation makes Groovy adds the interfaces of the delegated object to the
enclosing class. Since JDK12 types like `Integer`, `String` implement `Constable` this fails
when the class is loaded on JDK8 or 11.
See https://github.com/groovy/groovy-eclipse/issues/1436

java.lang.NoClassDefFoundError: java/lang/constant/Constable
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.datadog.appsec.event.data.ObjectIntrospectionSpecification.conversion of an element throws(ObjectIntrospectionSpecification.groovy:305)
Caused by: java.lang.ClassNotFoundException: java.lang.constant.Constable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more