Avoid duplicate debugger classes from ending up dd-java-agent (#7019)
* Change debugger-bootstrap to be an optional compileOnly dependency to dd-trace-core,
  otherwise it gets added multiple times in the final packaged dd-java-agent library.

  The build already arranges for debugger-bootstrap to be on the boot-class-path,
  so this is the simplest way to avoid the duplicate classes. The only additional
  change is to only call `DebuggerContext.handleException` when the live debugger
  product is enabled to make it a truly optional dependency, otherwise we get a
  NoClassDefFoundError in dd-trace-ot (which isn't meant to include the debugger.)

* fix tests - config flag is read on each exception

---------

Co-authored-by: jean-philippe bempel <jean-philippe.bempel@datadoghq.com>