Allow pre-Java 6 classes to be transformed in the debugger
Pre-Java 6 classes can contain JSR/RET instructions which are not
supported by ASM when the COMPUTE_FRAMES is used. This leads to
exceptions like this:

13:34:29.407 [Test worker] ERROR com.datadog.debugger.agent.DebuggerTransformer - Cannot write classfile for class: org.apache.felix.gogo.runtime.Pipe Exception:
java.lang.IllegalArgumentException: JSR/RET are not supported with computeFrames option
        at org.objectweb.asm.Frame.execute(Frame.java:1028)
        at org.objectweb.asm.MethodWriter.visitJumpInsn(MethodWriter.java:1147)
        at org.objectweb.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:79)
        at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:749)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:468)
        at com.datadog.debugger.agent.DebuggerTransformer.writeClassFile(DebuggerTransformer.java:492)
        ...

This uses ASM's JSRInlinerAdapter to rewrite the problematic JSR/RET
instructions as the class file is written.