fix: Failing :dd-java-agent:agent-tooling tests
When Groovy compiles this code against JDK 21 **but targeting Java 8**,

```
URLClassLoader loader = new URLClassLoader(classpath, null, null) {
    @Override
    Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        ...
    }
  }
```

Groovy will generate super class synthetic accessor methods like

* `super$2$loadClass(Ljava/lang/String;)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/String;Z)Ljava/lang/Class;`
* `super$2$loadClass(Ljava/lang/Module;Ljava/lang/String;)Ljava/lang/Class;`

`java.lang.Module` being missing from Java 8 won't run.

java.lang.NoClassDefFoundError: java/lang/Module
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.privateGetPublicMethods(Class.java:2930)
	at java.lang.Class.getMethods(Class.java:1643)
	at groovy.lang.MetaClassImpl.inheritInterfaceNewMetaMethods(MetaClassImpl.java:628)
	at groovy.lang.MetaClassImpl.fillMethodIndex(MetaClassImpl.java:368)
	at groovy.lang.MetaClassImpl.reinitialize(MetaClassImpl.java:3381)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3376)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:273)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:315)
	at datadog.trace.agent.test.BaseExceptionHandlerTest$1.$getStaticMetaClass(BaseExceptionHandlerTest.groovy)
	at datadog.trace.agent.test.BaseExceptionHandlerTest$1.<init>(BaseExceptionHandlerTest.groovy)
	at datadog.trace.agent.test.BaseExceptionHandlerTest.$spock_feature_1_1(BaseExceptionHandlerTest.groovy:131)
	...
Caused by: java.lang.ClassNotFoundException: java.lang.Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	...