Check target super-class implements `FieldBackedContextAccessor` before delegating to it (#6950)
This avoids the need to create (and catch) `NoSuchMethodError`s when we fail to inject the super-class.

For example starting the profiler before byte-buddy can trigger loading of various JDK concurrent classes that we would usually inject context into.